import * as THREE from 'three';
import { PointerLockControls } from 'three/addons/controls/PointerLockControls.js';
const CFG = Object.freeze({
  lot: { w: 10.000, d: 25.000 },
  house: { w: 7.076, d: 6.058, centerZ: 0.700, wall: 0.120 },
  modules: { left: 2.438, center: 2.200, right: 2.438 },
  balcony: { w: 7.076, d: 1.800 },
  levels: { ground: 0.000, social: 3.250, private: 6.250, roof: 9.220 },
  player: { height: 1.750, eye: 1.660, radius: 0.260, fov: 58 },
  drive: { minX: 0.850, maxX: 4.700, minZ: -12.300, maxZ: -2.329 },
  room: { partition: 0.100, bathW: 1.600, bathD: 2.200 },
});
const halfW = CFG.house.w / 2;
const halfD = CFG.house.d / 2;
const houseFront = CFG.house.centerZ - halfD;
const houseBack = CFG.house.centerZ + halfD;
const inner = Object.freeze({ west: -halfW + CFG.house.wall, east: halfW - CFG.house.wall, front: houseFront + CFG.house.wall, back: houseBack - CFG.house.wall });
const innerW = inner.east - inner.west;
const innerD = inner.back - inner.front;
const grossArea = CFG.house.w * CFG.house.d;
const clearArea = innerW * innerD;
const balconyArea = CFG.balcony.w * CFG.balcony.d;
const scene = new THREE.Scene();
scene.background = new THREE.Color(0xb8c5c7);
scene.fog = new THREE.Fog(0xb8c5c7, 28, 70);
const camera = new THREE.PerspectiveCamera(CFG.player.fov, innerWidth / innerHeight, 0.05, 110);
camera.position.set(-3.55, CFG.player.eye, -11.45);
const renderer = new THREE.WebGLRenderer({ antialias: true, powerPreference: 'high-performance' });
renderer.setSize(innerWidth, innerHeight);
renderer.setPixelRatio(Math.min(devicePixelRatio || 1, 1.0));
renderer.outputColorSpace = THREE.SRGBColorSpace;
renderer.toneMapping = THREE.ACESFilmicToneMapping;
renderer.toneMappingExposure = 1.0;
renderer.shadowMap.enabled = true;
renderer.shadowMap.type = THREE.PCFShadowMap;
renderer.shadowMap.autoUpdate = true;
document.body.prepend(renderer.domElement);
const controls = new PointerLockControls(camera, document.body);
const startEl = document.getElementById('start');
const enterEl = document.getElementById('enter');
const topbar = document.getElementById('topbar');
const selectedEl = document.getElementById('selected');
const feedbackEl = document.getElementById('feedback');
const feedbackTitle = document.getElementById('feedbackTitle');
const feedbackMeta = document.getElementById('feedbackMeta');
const feedbackText = document.getElementById('feedbackText');
const cancelFeedback = document.getElementById('cancelFeedback');
const sendFeedback = document.getElementById('sendFeedback');
const toastEl = document.getElementById('toast');
function toast(msg, error = false) {
  if (!toastEl) return;
  toastEl.textContent = msg;
  toastEl.style.background = error ? '#3b1818' : '#14231b';
  toastEl.style.opacity = '1';
  toastEl.style.transform = 'translateY(0)';
  clearTimeout(toastEl._t);
  toastEl._t = setTimeout(() => { toastEl.style.opacity = '0'; toastEl.style.transform = 'translateY(8px)'; }, 3200);
}
const MAT = {
  grass: new THREE.MeshLambertMaterial({ color: 0x557a49 }), ground: new THREE.MeshStandardMaterial({ color: 0x8b877d, roughness: 0.96 }), concrete: new THREE.MeshStandardMaterial({ color: 0x8f918c, roughness: 0.92 }), concreteDark: new THREE.MeshStandardMaterial({ color: 0x404743, roughness: 0.88 }), steel: new THREE.MeshStandardMaterial({ color: 0x1c2321, roughness: 0.42, metalness: 0.68 }), steelDark: new THREE.MeshStandardMaterial({ color: 0x0f1413, roughness: 0.38, metalness: 0.75 }), container: new THREE.MeshStandardMaterial({ color: 0x2a3431, roughness: 0.52, metalness: 0.52 }), wood: new THREE.MeshStandardMaterial({ color: 0x85522f, roughness: 0.72 }), woodLight: new THREE.MeshStandardMaterial({ color: 0xa87343, roughness: 0.70 }), wall: new THREE.MeshStandardMaterial({ color: 0xded9ce, roughness: 0.93 }), wallDark: new THREE.MeshStandardMaterial({ color: 0x303633, roughness: 0.90 }), glass: new THREE.MeshStandardMaterial({ color: 0xa7c4c5, transparent: true, opacity: 0.30, roughness: 0.18, metalness: 0.02, depthWrite: false, side: THREE.DoubleSide }), water: new THREE.MeshStandardMaterial({ color: 0x2b8591, transparent: true, opacity: 0.76, roughness: 0.22, metalness: 0.05 }), waterDark: new THREE.MeshStandardMaterial({ color: 0x225f67, transparent: true, opacity: 0.80, roughness: 0.25 }), rock: new THREE.MeshLambertMaterial({ color: 0x85867f }), soil: new THREE.MeshLambertMaterial({ color: 0x503623 }), leaf: new THREE.MeshLambertMaterial({ color: 0x35653a }), crop: new THREE.MeshLambertMaterial({ color: 0x5c9345 }), white: new THREE.MeshStandardMaterial({ color: 0xede9e1, roughness: 0.86 }), black: new THREE.MeshStandardMaterial({ color: 0x151918, roughness: 0.62 }), fabric: new THREE.MeshStandardMaterial({ color: 0x9d9488, roughness: 1.0 }), fabricDark: new THREE.MeshStandardMaterial({ color: 0x3d4641, roughness: 1.0 }), solar: new THREE.MeshStandardMaterial({ color: 0x183d54, roughness: 0.28, metalness: 0.55 }), warm: new THREE.MeshBasicMaterial({ color: 0xffc982 })
};
const GEO = { box: new THREE.BoxGeometry(1, 1, 1), cyl12: new THREE.CylinderGeometry(1, 1, 1, 12), sphere10: new THREE.SphereGeometry(1, 10, 7), rock: new THREE.DodecahedronGeometry(1, 0), cone6: new THREE.ConeGeometry(1, 1, 6) };
const collisionBoxes = [];
const selectableRoots = [];
function setTag(o, id, label, category = 'Elemento', extra = {}) { o.userData = { ...o.userData, id, label, category, selectable: true, ...extra }; selectableRoots.push(o); return o; }
function meshBox({ w, h, d, x = 0, y = h / 2, z = 0, mat = MAT.wall, id, label, category, collide = false, parent = scene, shadow = false, extra }) {
  const m = new THREE.Mesh(GEO.box, mat); m.scale.set(w, h, d); m.position.set(x, y, z); m.castShadow = shadow; m.receiveShadow = shadow || mat === MAT.concrete || mat === MAT.ground || mat === MAT.woodLight; parent.add(m); if (id) setTag(m, id, label || id, category, extra); if (collide) { m.updateMatrixWorld(true); collisionBoxes.push(new THREE.Box3().setFromObject(m)); } return m;
}
function cylinder({ r = 0.2, h = 1, x = 0, y = h / 2, z = 0, mat = MAT.wood, id, label, category, parent = scene, shadow = false }) { const m = new THREE.Mesh(GEO.cyl12, mat); m.scale.set(r, h, r); m.position.set(x, y, z); m.castShadow = shadow; m.receiveShadow = shadow; parent.add(m); if (id) setTag(m, id, label || id, category); return m; }
function wall({ id, label, x, yBase, z, w, h, d, mat = MAT.wall, parent = scene, collide = true, shadow = true }) { return meshBox({ w, h, d, x, y: yBase + h / 2, z, mat, id, label, category: 'Parede', parent, collide, shadow }); }
function furnitureBox(id, label, category, w, h, d, x, yBase, z, mat = MAT.wood) { return meshBox({ w, h, d, x, y: yBase + h / 2, z, mat, id, label, category, shadow: false }); }
scene.add(new THREE.HemisphereLight(0xe9f2f5, 0x4d5944, 1.7));
const sun = new THREE.DirectionalLight(0xffddb2, 3.0); sun.position.set(-10, 18, -14); sun.castShadow = true; sun.shadow.mapSize.set(1024, 1024); sun.shadow.camera.left = -12; sun.shadow.camera.right = 12; sun.shadow.camera.top = 18; sun.shadow.camera.bottom = -18; sun.shadow.camera.near = 1; sun.shadow.camera.far = 45; sun.shadow.bias = -0.00025; scene.add(sun);
const fill = new THREE.DirectionalLight(0xc8dcff, 0.55); fill.position.set(8, 7, 10); scene.add(fill);
meshBox({ w: CFG.lot.w, h: 0.08, d: CFG.lot.d, y: -0.04, mat: MAT.grass, id: 'LOT-10X25', label: 'Terreno 10,00 × 25,00 m', category: 'Terreno' });
wall({ id: 'MURO-O', label: 'Muro oeste', x: -4.94, yBase: 0, z: 0, w: 0.12, h: 1.65, d: 25, mat: MAT.concreteDark, shadow: false }); wall({ id: 'MURO-L', label: 'Muro leste', x: 4.94, yBase: 0, z: 0, w: 0.12, h: 1.65, d: 25, mat: MAT.concreteDark, shadow: false }); wall({ id: 'MURO-FUNDO', label: 'Muro fundos', x: 0, yBase: 0, z: 12.44, w: 10, h: 1.65, d: 0.12, mat: MAT.concreteDark, shadow: false }); wall({ id: 'MURO-FRENTE-E', label: 'Muro frente esquerdo', x: -3.86, yBase: 0, z: -12.44, w: 2.16, h: 1.55, d: 0.12, mat: MAT.concreteDark, shadow: false }); wall({ id: 'MURO-FRENTE-C', label: 'Muro frente central', x: -0.96, yBase: 0, z: -12.44, w: 1.64, h: 1.55, d: 0.12, mat: MAT.concreteDark, shadow: false }); wall({ id: 'MURO-FRENTE-D', label: 'Muro frente direito', x: 4.43, yBase: 0, z: -12.44, w: 1.02, h: 1.55, d: 0.12, mat: MAT.concreteDark, shadow: false });
meshBox({ w: 1.10, h: 1.48, d: 0.08, x: -2.48, y: 0.74, z: -12.37, mat: MAT.wood, id: 'PORTAO-PEDESTRE', label: 'Portão pedestre', category: 'Acesso', collide: true }); meshBox({ w: 3.50, h: 1.48, d: 0.08, x: 2.65, y: 0.74, z: -12.37, mat: MAT.wood, id: 'PORTAO-VEICULO', label: 'Portão de veículos', category: 'Acesso', collide: true }); meshBox({ w: CFG.drive.maxX - CFG.drive.minX, h: 0.025, d: CFG.drive.maxZ - CFG.drive.minZ, x: (CFG.drive.minX + CFG.drive.maxX) / 2, y: 0.0125, z: (CFG.drive.minZ + CFG.drive.maxZ) / 2, mat: MAT.ground, id: 'DRIVEWAY', label: 'Faixa veicular livre 3,85 m', category: 'Circulação', extra: { envelope: CFG.drive } }); meshBox({ w: 0.72, h: 0.025, d: 8.9, x: -3.25, y: 0.0125, z: -7.45, mat: MAT.ground, id: 'CAMINHO-PEDESTRE', label: 'Caminho pedestre', category: 'Circulação' });
const car = new THREE.Group(); car.position.set(2.73, 0, -10.05); scene.add(car); setTag(car, 'CARRO-REF', 'Carro de referência 1,82 × 4,28 m', 'Garagem'); meshBox({ w: 1.82, h: 0.58, d: 4.28, y: 0.43, mat: MAT.black, parent: car }); meshBox({ w: 1.46, h: 0.48, d: 1.72, y: 0.93, z: -0.15, mat: MAT.glass, parent: car }); for (const x of [-0.82, 0.82]) for (const z of [-1.45, 1.45]) { const wheel = new THREE.Mesh(new THREE.CylinderGeometry(0.30, 0.30, 0.18, 12), MAT.black); wheel.rotation.z = Math.PI / 2; wheel.position.set(x, 0.30, z); car.add(wheel); }
function pond({ id, label, x, z, rx, rz, mat }) { const g = new THREE.Group(); g.position.set(x, 0, z); scene.add(g); setTag(g, id, label, 'Água', { rx, rz }); const water = new THREE.Mesh(new THREE.CylinderGeometry(1, 1, 0.08, 32), mat); water.scale.set(rx, 1, rz); water.position.y = 0.02; g.add(water); const count = id === 'LAGO-NATURAL' ? 28 : 18; const rocks = new THREE.InstancedMesh(GEO.rock, MAT.rock, count); const dummy = new THREE.Object3D(); for (let i = 0; i < count; i++) { const a = i / count * Math.PI * 2; const s = 0.10 + (i % 4) * 0.018; dummy.position.set(Math.cos(a) * rx * 1.07, 0.09, Math.sin(a) * rz * 1.07); dummy.scale.set(s * 1.35, s * 0.68, s * 1.05); dummy.rotation.set(i * 0.13, i * 0.31, i * 0.17); dummy.updateMatrix(); rocks.setMatrixAt(i, dummy.matrix); } g.add(rocks); return g; }
pond({ id: 'LAGO-NATURAL', label: 'Lago natural de banho', x: -2.78, z: -7.15, rx: 1.45, rz: 2.05, mat: MAT.water }); pond({ id: 'LAGO-PEIXES', label: 'Lago de peixes', x: -0.42, z: -9.55, rx: 0.70, rz: 1.18, mat: MAT.waterDark }); meshBox({ w: 1.05, h: 0.12, d: 2.30, x: -1.25, y: 0.12, z: -6.65, mat: MAT.woodLight, id: 'DECK-LAGO', label: 'Deck do lago natural', category: 'Lazer' }); meshBox({ w: 0.72, h: 0.08, d: 1.18, x: -2.00, y: 0.10, z: -5.57, mat: MAT.woodLight, id: 'PASSARELA-LAGO', label: 'Passarela do lago', category: 'Lazer' }); cylinder({ r: 0.27, h: 0.58, x: -0.36, y: 0.29, z: -7.55, mat: MAT.black, id: 'FILTRO-BIO-1', label: 'Filtro biológico 1', category: 'Sistema de água' }); cylinder({ r: 0.27, h: 0.58, x: 0.23, y: 0.29, z: -7.55, mat: MAT.black, id: 'FILTRO-BIO-2', label: 'Filtro biológico 2', category: 'Sistema de água' }); cylinder({ r: 0.50, h: 0.68, x: -3.92, y: 0.34, z: -10.90, mat: MAT.concrete, id: 'CISTERNA', label: 'Cisterna de captação de chuva', category: 'Sistema de água' });
function addSteelFrame() { const xs = [-halfW + 0.16, 0, halfW - 0.16]; const zs = [houseFront + 0.16, CFG.house.centerZ, houseBack - 0.16]; for (const x of xs) for (const z of zs) meshBox({ w: 0.18, h: CFG.levels.private + 2.82, d: 0.18, x, y: (CFG.levels.private + 2.82) / 2, z, mat: MAT.steelDark, id: `PILAR-${x.toFixed(2)}-${z.toFixed(2)}`, label: 'Pilar metálico independente', category: 'Estrutura', collide: true, shadow: true }); for (const y of [CFG.levels.social, CFG.levels.private]) for (const z of [houseFront + 0.10, CFG.house.centerZ, houseBack - 0.10]) meshBox({ w: CFG.house.w + 0.15, h: 0.18, d: 0.14, x: 0, y: y - 0.09, z, mat: MAT.steelDark, shadow: true }); }
addSteelFrame();
function addFloor(y, id, label) { meshBox({ w: CFG.house.w, h: 0.14, d: CFG.house.d, x: 0, y: y - 0.07, z: CFG.house.centerZ, mat: MAT.woodLight, id, label, category: 'Pavimento' }); }
addFloor(CFG.levels.social, 'PISO-SOCIAL', 'Pavimento social 7,076 × 6,058 m'); addFloor(CFG.levels.private, 'PISO-INTIMO', 'Pavimento íntimo 7,076 × 6,058 m'); meshBox({ w: CFG.house.w, h: 0.05, d: CFG.house.d, x: 0, y: 0.025, z: CFG.house.centerZ, mat: MAT.concrete, id: 'PISO-TERREO', label: 'Térreo funcional sob pilotis', category: 'Pavimento' });
function addShell(yBase, prefix) { const h = 2.82; wall({ id: `${prefix}-O`, label: `${prefix} fachada oeste`, x: -halfW + CFG.house.wall / 2, yBase, z: CFG.house.centerZ, w: CFG.house.wall, h, d: CFG.house.d, mat: MAT.container, shadow: true }); wall({ id: `${prefix}-L`, label: `${prefix} fachada leste`, x: halfW - CFG.house.wall / 2, yBase, z: CFG.house.centerZ, w: CFG.house.wall, h, d: CFG.house.d, mat: MAT.container, shadow: true }); wall({ id: `${prefix}-B1`, label: `${prefix} fundo esquerdo`, x: -2.65, yBase, z: houseBack - CFG.house.wall / 2, w: 1.55, h, d: CFG.house.wall, mat: MAT.container, shadow: true }); wall({ id: `${prefix}-B2`, label: `${prefix} fundo direito`, x: 2.65, yBase, z: houseBack - CFG.house.wall / 2, w: 1.55, h, d: CFG.house.wall, mat: MAT.container, shadow: true }); meshBox({ w: 3.75, h: 2.25, d: 0.025, x: 0, y: yBase + 1.14, z: houseBack - 0.05, mat: MAT.glass, id: `${prefix}-GLASS-B`, label: 'Esquadria traseira ampla', category: 'Esquadria' }); meshBox({ w: CFG.house.w - 0.28, h: 2.30, d: 0.025, x: 0, y: yBase + 1.18, z: houseFront + 0.055, mat: MAT.glass, id: `${prefix}-GLASS-F`, label: 'Fachada frontal envidraçada', category: 'Esquadria' }); for (const x of [-2.65, -1.32, 0, 1.32, 2.65]) meshBox({ w: 0.045, h: 2.48, d: 0.055, x, y: yBase + 1.24, z: houseFront + 0.035, mat: MAT.steelDark }); meshBox({ w: CFG.house.w, h: 0.14, d: 0.10, x: 0, y: yBase + 2.75, z: houseFront + 0.01, mat: MAT.steelDark, shadow: true }); }
addShell(CFG.levels.social, 'SOCIAL'); addShell(CFG.levels.private, 'INTIMO'); for (const y of [CFG.levels.social, CFG.levels.private]) { const yy = y + 2.68; for (const x of [-1.10, 1.10]) meshBox({ w: 0.035, h: 0.09, d: CFG.house.d - 0.20, x, y: yy, z: CFG.house.centerZ, mat: MAT.steelDark }); }
function addBalcony(yBase, prefix) { const centerZ = houseFront - CFG.balcony.d / 2; const g = new THREE.Group(); scene.add(g); setTag(g, `${prefix}-SACADA`, `Sacada externa ${CFG.balcony.w.toFixed(3)} × ${CFG.balcony.d.toFixed(3)} m`, 'Sacada', { externalToLivingEnvelope: true, area: balconyArea }); meshBox({ w: CFG.balcony.w, h: 0.12, d: CFG.balcony.d, x: 0, y: yBase - 0.06, z: centerZ, mat: MAT.woodLight, parent: g }); const railZ = houseFront - CFG.balcony.d + 0.04; meshBox({ w: CFG.balcony.w, h: 0.045, d: 0.045, x: 0, y: yBase + 1.02, z: railZ, mat: MAT.steelDark, parent: g }); for (let x = -halfW; x <= halfW + 0.001; x += 0.55) meshBox({ w: 0.025, h: 1.00, d: 0.025, x: Math.min(x, halfW), y: yBase + 0.50, z: railZ, mat: MAT.steelDark, parent: g }); for (const side of [-1, 1]) meshBox({ w: 0.035, h: 1.00, d: CFG.balcony.d, x: side * (halfW - 0.02), y: yBase + 0.50, z: centerZ, mat: MAT.steelDark, parent: g }); }
addBalcony(CFG.levels.social, 'SOCIAL'); addBalcony(CFG.levels.private, 'INTIMO');
meshBox({ w: CFG.house.w + 0.80, h: 0.16, d: CFG.house.d + 0.85, x: 0, y: CFG.levels.roof, z: CFG.house.centerZ, mat: MAT.steel, id: 'COBERTURA', label: 'Cobertura independente ventilada', category: 'Cobertura', shadow: true }); for (let r = 0; r < 2; r++) for (let c = 0; c < 4; c++) meshBox({ w: 1.34, h: 0.045, d: 1.48, x: -2.15 + c * 1.43, y: CFG.levels.roof + 0.18, z: CFG.house.centerZ - 0.82 + r * 1.62, mat: MAT.solar, id: `FV-${r + 1}-${c + 1}`, label: 'Painel fotovoltaico', category: 'Energia' }); cylinder({ r: 0.34, h: 0.72, x: 2.70, y: CFG.levels.roof + 0.45, z: CFG.house.centerZ + 1.78, mat: MAT.concrete, id: 'RESERVATORIO', label: 'Reservatório operacional', category: 'Sistema de água' });
function externalStair(prefix, baseY, fromZ, toZ) { const g = new THREE.Group(); scene.add(g); setTag(g, prefix, 'Escada externa', 'Escada', { externalToLivingEnvelope: true }); const steps = 17; for (let i = 0; i < steps; i++) { const t = i / (steps - 1); meshBox({ w: 0.88, h: 0.08, d: 0.27, x: 4.04, y: baseY + t * 3.00, z: fromZ + (toZ - fromZ) * t, mat: MAT.woodLight, parent: g }); } meshBox({ w: 0.045, h: 1.0, d: Math.abs(toZ - fromZ) + 0.5, x: 4.48, y: baseY + 1.8, z: (fromZ + toZ) / 2, mat: MAT.steelDark, parent: g }); }
externalStair('ESC-G-S', 0.18, 3.85, -0.20); externalStair('ESC-S-I', 3.25, -0.20, 3.85);
const serviceDepth = 2.60, serviceFront = inner.back - serviceDepth, serviceCenterZ = (serviceFront + inner.back) / 2, availableGroundW = innerW - 2 * CFG.room.partition, groundScale = availableGroundW / 7.20, workshopW = 3.20 * groundScale, storageW = 2.00 * groundScale, laundryW = 2.00 * groundScale, div1X = inner.west + workshopW + CFG.room.partition / 2, div2X = inner.west + workshopW + CFG.room.partition + storageW + CFG.room.partition / 2;
wall({ id: 'TER-FUNDO', label: 'Parede de serviços', x: 0, yBase: 0, z: houseBack - 0.07, w: CFG.house.w - 0.24, h: 2.55, d: 0.10, mat: MAT.wallDark, shadow: true }); wall({ id: 'TER-DIV-1', label: 'Divisória oficina/depósito', x: div1X, yBase: 0, z: serviceCenterZ, w: CFG.room.partition, h: 2.55, d: serviceDepth, mat: MAT.wallDark, shadow: false }); wall({ id: 'TER-DIV-2', label: 'Divisória depósito/lavanderia', x: div2X, yBase: 0, z: serviceCenterZ, w: CFG.room.partition, h: 2.55, d: serviceDepth, mat: MAT.wallDark, shadow: false }); furnitureBox('BANCADA-OFICINA', 'Bancada de oficina', 'Oficina', Math.min(2.2, workshopW - 0.30), 0.85, 0.62, inner.west + workshopW / 2, 0, inner.back - 0.48, MAT.wood); for (let i = 0; i < 3; i++) furnitureBox(`PRAT-DEP-${i + 1}`, 'Prateleira depósito', 'Depósito', storageW - 0.25, 0.07, 0.40, div1X + 0.05 + storageW / 2, 0.45 + i * 0.55, inner.back - 0.35, MAT.wood); furnitureBox('LAVADORA', 'Lavadora', 'Lavanderia', 0.66, 0.88, 0.66, div2X + 0.52, 0, inner.back - 0.48, MAT.white); furnitureBox('SECADORA', 'Secadora', 'Lavanderia', 0.66, 0.88, 0.66, div2X + 1.24, 0, inner.back - 0.48, MAT.white); furnitureBox('BANCADA-GOURMET', 'Bancada gourmet', 'Gourmet', 2.65, 0.90, 0.65, -1.55, 0, -1.10, MAT.wood); furnitureBox('CHURRASQUEIRA', 'Churrasqueira', 'Gourmet', 0.82, 1.45, 0.64, -3.00, 0, -1.10, MAT.steel); furnitureBox('MESA-GOURMET', 'Mesa gourmet', 'Gourmet', 1.95, 0.76, 0.90, -1.45, 0, 0.05, MAT.woodLight); for (const x of [-2.20, -1.45, -0.70]) for (const z of [-0.62, 0.66]) furnitureBox(`CADEIRA-GOURMET-${x}-${z}`, 'Cadeira gourmet', 'Gourmet', 0.38, 0.45, 0.38, x, 0, z, MAT.wood); meshBox({ w: 2.55, h: 0.018, d: 3.40, x: 2.10, y: 0.018, z: -0.50, mat: MAT.concreteDark, id: 'VAGA-COBERTA', label: 'Vaga coberta sob pilotis', category: 'Garagem' });
const sY = CFG.levels.social; const bathSocial = { west: inner.east - CFG.room.bathW, east: inner.east, front: inner.back - CFG.room.bathD, back: inner.back };
wall({ id: 'BAN-SOC-O', label: 'Banheiro social parede oeste', x: bathSocial.west - CFG.room.partition / 2, yBase: sY, z: (bathSocial.front + bathSocial.back) / 2, w: CFG.room.partition, h: 2.62, d: CFG.room.bathD, mat: MAT.wall, shadow: false }); wall({ id: 'BAN-SOC-F', label: 'Banheiro social parede frontal', x: bathSocial.west + 0.15, yBase: sY, z: bathSocial.front - CFG.room.partition / 2, w: 0.30, h: 2.62, d: CFG.room.partition, mat: MAT.wall, shadow: false }); wall({ id: 'BAN-SOC-F2', label: 'Banheiro social parede frontal', x: bathSocial.east - 0.29, yBase: sY, z: bathSocial.front - CFG.room.partition / 2, w: 0.58, h: 2.62, d: CFG.room.partition, mat: MAT.wall, shadow: false }); furnitureBox('BAN-SOC-VASO', 'Vaso sanitário social', 'Banheiro', 0.48, 0.42, 0.66, 2.05, sY, 3.02, MAT.white); furnitureBox('BAN-SOC-PIA', 'Pia social', 'Banheiro', 0.72, 0.82, 0.44, 2.90, sY, 3.08, MAT.wood); meshBox({ w: 0.74, h: 2.02, d: 0.025, x: 2.93, y: sY + 1.01, z: 1.60, mat: MAT.glass, id: 'BAN-SOC-BOX', label: 'Box banheiro social', category: 'Banheiro' }); furnitureBox('COZ-BANCADA', 'Bancada cozinha', 'Cozinha', 2.90, 0.92, 0.64, -1.90, sY, 3.18, MAT.wood); furnitureBox('COZ-GELADEIRA', 'Geladeira', 'Cozinha', 0.74, 1.85, 0.68, -3.00, sY, 2.50, MAT.steel); furnitureBox('COZ-FOGAO', 'Fogão/cooktop', 'Cozinha', 0.76, 0.90, 0.66, -1.20, sY, 3.14, MAT.steel); furnitureBox('COZ-ILHA', 'Ilha da cozinha', 'Cozinha', 2.10, 0.92, 0.82, -1.35, sY, 1.38, MAT.woodLight); for (let i = 0; i < 3; i++) furnitureBox(`BANCO-ILHA-${i + 1}`, 'Banco da ilha', 'Cozinha', 0.36, 0.48, 0.36, -2.05 + i * 0.70, sY, 0.82, MAT.wood); furnitureBox('MESA-JANTAR', 'Mesa de jantar', 'Jantar', 1.72, 0.75, 0.88, -1.65, sY, -1.08, MAT.woodLight); for (const x of [-2.25, -1.65, -1.05]) for (const z of [-1.66, -0.50]) furnitureBox(`CAD-JANTAR-${x}-${z}`, 'Cadeira de jantar', 'Jantar', 0.34, 0.44, 0.34, x, sY, z, MAT.wood); furnitureBox('SOFA', 'Sofá 3 lugares', 'Sala', 2.05, 0.76, 0.84, 1.20, sY, -0.55, MAT.fabric); furnitureBox('MESA-CENTRO', 'Mesa de centro', 'Sala', 1.05, 0.28, 0.58, 0.35, sY, -1.55, MAT.wood); furnitureBox('TV-SALA', 'Painel / TV da sala', 'Sala', 1.55, 0.90, 0.10, 3.27, sY + 0.70, -0.45, MAT.black);
const pY = CFG.levels.private, leftRoomW = 3.40, axisX = inner.west + leftRoomW, splitZ = CFG.house.centerZ, bedroomDepth = (innerD - CFG.room.partition) / 2, axisWallX = axisX + CFG.room.partition / 2; const axisSegments = [[inner.front, -0.55], [0.25, 1.10], [1.90, inner.back]]; axisSegments.forEach(([za, zb], i) => wall({ id: `INT-DIV-EIXO-${i+1}`, label: 'Eixo íntimo quartos/circulação', x: axisWallX, yBase: pY, z: (za + zb) / 2, w: CFG.room.partition, h: 2.68, d: zb - za, mat: MAT.wall, shadow: false })); wall({ id: 'INT-DIV-QUARTOS', label: 'Divisória casal/filhos', x: inner.west + leftRoomW / 2, yBase: pY, z: splitZ, w: leftRoomW, h: 2.68, d: CFG.room.partition, mat: MAT.wall, shadow: false });
const childZ = splitZ + CFG.room.partition / 2 + bedroomDepth / 2; for (let i = 0; i < 3; i++) { const x = -2.78 + i * 1.05; furnitureBox(`CAMA-FILHO-${i + 1}`, `Cama filho ${i + 1}`, 'Quarto 3 filhos', 0.78, 0.44, 1.88, x, pY, childZ + 0.28, MAT.woodLight); furnitureBox(`COLCHAO-FILHO-${i + 1}`, 'Colchão', 'Quarto 3 filhos', 0.73, 0.16, 1.78, x, pY + 0.44, childZ + 0.28, MAT.white); } furnitureBox('BANCADA-FILHOS', 'Bancada estudo 3 filhos', 'Quarto 3 filhos', 2.65, 0.72, 0.42, -1.72, pY, splitZ + 0.33, MAT.wood); for (let i = 0; i < 3; i++) furnitureBox(`CAD-FILHO-${i + 1}`, 'Cadeira de estudo', 'Quarto 3 filhos', 0.34, 0.46, 0.34, -2.55 + i * 0.82, pY, splitZ + 0.78, MAT.fabricDark);
const masterZ = splitZ - CFG.room.partition / 2 - bedroomDepth / 2; furnitureBox('CAMA-CASAL', 'Cama casal queen', 'Quarto casal', 1.58, 0.42, 1.98, -2.18, pY, masterZ - 0.10, MAT.woodLight); furnitureBox('COLCHAO-CASAL', 'Colchão casal', 'Quarto casal', 1.52, 0.16, 1.90, -2.18, pY + 0.42, masterZ - 0.10, MAT.white); furnitureBox('GUARDA-ROUPA-CASAL', 'Guarda-roupa casal', 'Quarto casal', 1.42, 2.15, 0.55, -0.72, pY, inner.front + 0.34, MAT.wall); furnitureBox('CRIADO-CASAL', 'Criado-mudo', 'Quarto casal', 0.42, 0.46, 0.38, -3.12, pY, masterZ - 0.15, MAT.wood);
const bathP = { west: inner.east - CFG.room.bathW, east: inner.east, front: inner.back - CFG.room.bathD, back: inner.back }; wall({ id: 'BAN-INT-O', label: 'Banheiro íntimo parede oeste', x: bathP.west - CFG.room.partition / 2, yBase: pY, z: (bathP.front + bathP.back) / 2, w: CFG.room.partition, h: 2.68, d: CFG.room.bathD, mat: MAT.wall, shadow: false }); wall({ id: 'BAN-INT-F', label: 'Banheiro íntimo parede frontal', x: bathP.west + 0.15, yBase: pY, z: bathP.front - CFG.room.partition / 2, w: 0.30, h: 2.68, d: CFG.room.partition, mat: MAT.wall, shadow: false }); wall({ id: 'BAN-INT-F2', label: 'Banheiro íntimo parede frontal', x: bathP.east - 0.29, yBase: pY, z: bathP.front - CFG.room.partition / 2, w: 0.58, h: 2.68, d: CFG.room.partition, mat: MAT.wall, shadow: false }); furnitureBox('BAN-INT-VASO', 'Vaso sanitário íntimo', 'Banheiro', 0.48, 0.42, 0.66, 2.08, pY, 3.02, MAT.white); furnitureBox('BAN-INT-PIA', 'Pia banheiro íntimo', 'Banheiro', 0.70, 0.82, 0.42, 2.88, pY, 3.08, MAT.wood); furnitureBox('BANHEIRA', 'Banheira compacta', 'Banheiro', 0.72, 0.54, 1.30, 2.88, pY, 1.95, MAT.white); furnitureBox('MESA-GAMER', 'Bancada gamer', 'Escritório/Gamer', 2.00, 0.76, 0.62, 2.12, pY, -1.62, MAT.wood); for (let i = 0; i < 2; i++) furnitureBox(`MONITOR-${i + 1}`, 'Monitor gamer', 'Escritório/Gamer', 0.66, 0.42, 0.06, 1.68 + i * 0.88, pY + 0.82, -1.88, MAT.black); furnitureBox('CADEIRA-GAMER', 'Cadeira gamer', 'Escritório/Gamer', 0.52, 0.80, 0.52, 2.10, pY, -0.72, MAT.fabricDark); furnitureBox('PC-GAMER', 'PC gamer', 'Escritório/Gamer', 0.42, 0.90, 0.46, 3.05, pY, -1.38, MAT.black);
function raisedBed(id, x, z) { const g = new THREE.Group(); g.position.set(x, 0, z); scene.add(g); setTag(g, id, 'Canteiro elevado', 'Horta'); meshBox({ w: 1.48, h: 0.28, d: 0.60, y: 0.14, mat: MAT.wood, parent: g }); meshBox({ w: 1.35, h: 0.10, d: 0.46, y: 0.31, mat: MAT.soil, parent: g }); for (let j = 0; j < 4; j++) { const sprout = new THREE.Mesh(GEO.cone6, MAT.crop); sprout.scale.set(0.06, 0.18, 0.06); sprout.position.set(-0.48 + j * 0.32, 0.46, 0); g.add(sprout); } }
let bedN = 0; for (const x of [-1.45, 0.30]) for (const z of [6.15, 7.00, 7.85, 8.70]) raisedBed(`HORTA-${++bedN}`, x, z);
const greenhouse = new THREE.Group(); greenhouse.position.set(-3.28, 0, 9.70); scene.add(greenhouse); setTag(greenhouse, 'ESTUFA', 'Estufa de cultivo', 'Estufa'); meshBox({ w: 2.15, h: 0.08, d: 3.35, y: 0.04, mat: MAT.concrete, parent: greenhouse }); for (const x of [-1.02, 1.02]) for (const z of [-1.60, 1.60]) meshBox({ w: 0.06, h: 1.95, d: 0.06, x, y: 0.98, z, mat: MAT.steelDark, parent: greenhouse }); meshBox({ w: 2.05, h: 1.70, d: 0.025, y: 0.90, z: -1.60, mat: MAT.glass, parent: greenhouse }); meshBox({ w: 2.05, h: 1.70, d: 0.025, y: 0.90, z: 1.60, mat: MAT.glass, parent: greenhouse });
const aviary = new THREE.Group(); aviary.position.set(0.25, 0, 10.08); scene.add(aviary); setTag(aviary, 'AVIARIO', 'Galinheiro / aviário', 'Produção animal'); meshBox({ w: 2.45, h: 0.10, d: 2.20, y: 0.05, mat: MAT.soil, parent: aviary }); for (const x of [-1.15, 1.15]) for (const z of [-1.02, 1.02]) meshBox({ w: 0.06, h: 1.75, d: 0.06, x, y: 0.88, z, mat: MAT.wood, parent: aviary }); meshBox({ w: 2.50, h: 0.10, d: 2.25, y: 1.80, mat: MAT.steel, parent: aviary }); meshBox({ w: 1.72, h: 2.00, d: 2.10, x: 3.45, y: 1.00, z: 10.15, mat: MAT.wallDark, id: 'DEP-FERR', label: 'Depósito de ferramentas', category: 'Apoio', shadow: true }); for (let i = 0; i < 3; i++) meshBox({ w: 0.88, h: 0.68, d: 0.98, x: -3.42 + i * 0.95, y: 0.34, z: 6.25, mat: MAT.wood, id: `COMPOST-${i + 1}`, label: `Composteira ${i + 1}`, category: 'Compostagem' }); for (let r = 0; r < 5; r++) meshBox({ w: 0.18, h: 0.25, d: 1.30, x: 4.10, y: 0.48 + r * 0.36, z: 6.75, mat: MAT.wood, id: `HORTA-V-${r + 1}`, label: 'Horta vertical', category: 'Horta vertical' }); meshBox({ w: 1.12, h: 0.16, d: 1.55, x: 3.00, y: 0.08, z: 7.10, mat: MAT.soil, id: 'JARDIM-FILTRANTE', label: 'Jardim filtrante / reuso', category: 'Reuso' });
const treePositions = []; for (const z of [-10.4, -8.0, -5.6, -3.2, -0.7, 1.8, 4.4, 7.0, 9.4, 11.2]) treePositions.push([-4.35, z]); for (const z of [-0.5, 2.1, 4.7, 7.3, 9.7, 11.2]) treePositions.push([4.38, z]); for (const x of [-3.5, -1.75, 0, 1.75, 3.5]) treePositions.push([x, 11.65]); const trunks = new THREE.InstancedMesh(GEO.cyl12, MAT.wood, treePositions.length), crowns = new THREE.InstancedMesh(GEO.sphere10, MAT.leaf, treePositions.length), dummy = new THREE.Object3D(); treePositions.forEach(([x, z], i) => { const s = 0.62 + (i % 3) * 0.07; dummy.position.set(x, 0.65 * s, z); dummy.scale.set(0.10 * s, 1.30 * s, 0.10 * s); dummy.updateMatrix(); trunks.setMatrixAt(i, dummy.matrix); dummy.position.set(x, 1.55 * s, z); dummy.scale.set(0.55 * s, 0.70 * s, 0.55 * s); dummy.updateMatrix(); crowns.setMatrixAt(i, dummy.matrix); }); scene.add(trunks, crowns);
for (const [x, y, z] of [[-2.0, sY + 2.35, -0.4], [1.8, sY + 2.35, -0.2], [-2.0, pY + 2.32, -0.5], [2.1, pY + 2.32, -0.7]]) { const bulb = new THREE.PointLight(0xffb56c, 12, 4.5, 2.0); bulb.position.set(x, y, z); scene.add(bulb); } for (const [x, z] of [[-4.1, -10.8], [-4.1, -6.5], [-4.1, -2.6], [4.1, 4.2], [4.1, 8.6]]) { const m = new THREE.Mesh(new THREE.SphereGeometry(0.055, 8, 6), MAT.warm); m.position.set(x, 0.34, z); scene.add(m); }
const humanGauge = new THREE.Group(); humanGauge.visible = false; humanGauge.position.set(-3.85, 0.01, -3.55); scene.add(humanGauge); setTag(humanGauge, 'ESCALA-HUMANA', 'Referência humana 1,75 m', 'Escala'); meshBox({ w: 0.035, h: CFG.player.height, d: 0.035, x: 0, y: CFG.player.height / 2, z: 0, mat: MAT.steelDark, parent: humanGauge }); for (const y of [0.5, 1.0, 1.5, CFG.player.height]) meshBox({ w: 0.22, h: 0.02, d: 0.035, x: 0.10, y, z: 0, mat: y === CFG.player.height ? MAT.warm : MAT.steelDark, parent: humanGauge }); const head = new THREE.Mesh(new THREE.SphereGeometry(0.10, 10, 7), MAT.woodLight); head.position.set(0.35, 1.65, 0); humanGauge.add(head); meshBox({ w: 0.28, h: 0.72, d: 0.16, x: 0.35, y: 1.15, z: 0, mat: MAT.steelDark, parent: humanGauge });
function rectIntersects(a, b) { return !(a.maxX <= b.minX || a.minX >= b.maxX || a.maxZ <= b.minZ || a.minZ >= b.maxZ); } function objectXZBounds(o) { const b = new THREE.Box3().setFromObject(o); return { minX: b.min.x, maxX: b.max.x, minZ: b.min.z, maxZ: b.max.z }; } const driveViolations = []; for (const id of ['LAGO-NATURAL', 'LAGO-PEIXES', 'DECK-LAGO', 'PASSARELA-LAGO', 'FILTRO-BIO-1', 'FILTRO-BIO-2']) { const o = selectableRoots.find(v => v.userData.id === id); if (o && rectIntersects(objectXZBounds(o), CFG.drive)) driveViolations.push(id); }
const QA = { version: 'v0.9-consolidated', unit: '1u = 1m', lot: [CFG.lot.w, CFG.lot.d], livingEnvelopeEachFloor: [CFG.house.w, CFG.house.d], grossAreaEachFloor: +grossArea.toFixed(3), approximateClearAreaEachFloor: +clearArea.toFixed(3), centralBand: CFG.modules.center, balcony: { size: [CFG.balcony.w, CFG.balcony.d], area: +balconyArea.toFixed(3), externalToLivingEnvelope: true }, socialBathroom: [CFG.room.bathW, CFG.room.bathD], privateBathroom: [CFG.room.bathW, CFG.room.bathD], privateBedrooms: { width: leftRoomW, depth: +bedroomDepth.toFixed(3), reason: 'cotas 3,40 x 3,40 da prancha não cabem duas vezes dentro de 6,058 m externos' }, driveway: CFG.drive, driveViolations, pass: driveViolations.length === 0 }; window.__CASA_QA__ = QA; console.info('[Casa Contreras] QA v0.9', QA);
const keys = Object.create(null); let activeLevel = 0, velocityY = 0, onGround = true, selected = null; const tmpForward = new THREE.Vector3(), tmpRight = new THREE.Vector3(), up = new THREE.Vector3(0, 1, 0), playerBox = new THREE.Box3();
function floorEyeY() { if (activeLevel === 1) return CFG.levels.social + CFG.player.eye; if (activeLevel === 2) return CFG.levels.private + CFG.player.eye; return CFG.player.eye; }
function teleport(level) { activeLevel = level; if (level === 0) camera.position.set(-2.45, CFG.player.eye, -4.80); if (level === 1) camera.position.set(0.10, CFG.levels.social + CFG.player.eye, -0.90); if (level === 2) camera.position.set(0.55, CFG.levels.private + CFG.player.eye, -0.85); velocityY = 0; onGround = true; toast(`Nível: ${level === 0 ? 'térreo' : level === 1 ? 'social' : 'íntimo'}`); }
function canMove(pos) { if (pos.x < -4.72 || pos.x > 4.72 || pos.z < -12.18 || pos.z > 12.18) return false; const footY = floorEyeY() - CFG.player.eye; playerBox.min.set(pos.x - CFG.player.radius, footY + 0.04, pos.z - CFG.player.radius); playerBox.max.set(pos.x + CFG.player.radius, footY + CFG.player.height, pos.z + CFG.player.radius); for (const b of collisionBoxes) if (playerBox.intersectsBox(b)) return false; return true; }
addEventListener('keydown', e => { keys[e.code] = true; if (e.code === 'Digit1') teleport(0); if (e.code === 'Digit2') teleport(1); if (e.code === 'Digit3') teleport(2); if (e.code === 'KeyH') humanGauge.visible = !humanGauge.visible; if (e.code === 'KeyF') exportLocalFeedbacks(); if (e.code === 'Space' && onGround) { velocityY = 4.1; onGround = false; } }); addEventListener('keyup', e => { keys[e.code] = false; });
function updateMovement(dt) { if (!controls.isLocked) return; const speed = keys.ShiftLeft || keys.ShiftRight ? 4.0 : 2.25, f = (keys.KeyW ? 1 : 0) - (keys.KeyS ? 1 : 0), s = (keys.KeyD ? 1 : 0) - (keys.KeyA ? 1 : 0); if (f || s) { camera.getWorldDirection(tmpForward); tmpForward.y = 0; tmpForward.normalize(); tmpRight.crossVectors(tmpForward, up).normalize(); const candidate = camera.position.clone(); candidate.addScaledVector(tmpForward, f * speed * dt); candidate.addScaledVector(tmpRight, s * speed * dt); if (canMove(candidate)) camera.position.copy(candidate); } velocityY -= 9.8 * dt; camera.position.y += velocityY * dt; const fy = floorEyeY(); if (camera.position.y <= fy) { camera.position.y = fy; velocityY = 0; onGround = true; } }
const raycaster = new THREE.Raycaster(), centerNdc = new THREE.Vector2(0, 0); function selectableAncestor(o) { let n = o; while (n && n !== scene) { if (n.userData?.selectable) return n; n = n.parent; } return null; } function pick() { raycaster.setFromCamera(centerNdc, camera); const hits = raycaster.intersectObjects(scene.children, true); for (const h of hits) { const root = selectableAncestor(h.object); if (root) return { root, point: h.point }; } return null; }
let hoverElapsed = 0; function updateHover(dt) { if (!controls.isLocked || !selectedEl) return; hoverElapsed += dt; if (hoverElapsed < 0.12) return; hoverElapsed = 0; const hit = pick(); if (hit) { selectedEl.textContent = hit.root.userData.label; selectedEl.style.opacity = '1'; } else selectedEl.style.opacity = '0'; }
addEventListener('mousedown', e => { if (e.button !== 0 || !controls.isLocked) return; const hit = pick(); if (!hit) return; selected = hit; controls.unlock(); feedbackEl.style.display = 'grid'; feedbackTitle.textContent = `${hit.root.userData.label} [${hit.root.userData.id}]`; feedbackMeta.textContent = [`Categoria: ${hit.root.userData.category}`, `ID: ${hit.root.userData.id}`, `Clique: x=${hit.point.x.toFixed(3)} y=${hit.point.y.toFixed(3)} z=${hit.point.z.toFixed(3)}`, `Câmera: x=${camera.position.x.toFixed(3)} y=${camera.position.y.toFixed(3)} z=${camera.position.z.toFixed(3)}`, `Corpo da casa: 7,076 × 6,058 m`, `Sacada: 7,076 × 1,800 m — EXTERNA ao corpo da casa`, `Área bruta/pavimento: ${grossArea.toFixed(2)} m²`, `Versão: v0.9-consolidated`].join('\n'); feedbackText.value = ''; setTimeout(() => feedbackText.focus(), 50); });
cancelFeedback?.addEventListener('click', () => { feedbackEl.style.display = 'none'; selected = null; controls.lock(); });
function collectLocalFeedbacks() { const items = []; for (let i = 0; i < localStorage.length; i++) { const key = localStorage.key(i); if (!key || !key.startsWith('casa-feedback')) continue; try { items.push({ key, value: JSON.parse(localStorage.getItem(key)) }); } catch { items.push({ key, value: localStorage.getItem(key) }); } } return items; }
async function exportLocalFeedbacks() { const items = collectLocalFeedbacks(); const payload = JSON.stringify({ exportedAt: new Date().toISOString(), count: items.length, feedbacks: items }, null, 2); try { await navigator.clipboard.writeText(payload); toast(`${items.length} feedback(s) locais copiados. Cole no chat para eu recuperar.`); } catch { const blob = new Blob([payload], { type: 'application/json' }); const url = URL.createObjectURL(blob); const a = document.createElement('a'); a.href = url; a.download = 'casa-contreras-feedbacks.json'; a.click(); URL.revokeObjectURL(url); toast(`${items.length} feedback(s) exportados em JSON.`); } }
sendFeedback.textContent = 'Salvar + abrir Issue no GitHub'; sendFeedback?.addEventListener('click', e => { e.preventDefault(); e.stopImmediatePropagation(); if (!selected) return; const text = feedbackText.value.trim(); if (!text) { toast('Escreva o feedback primeiro.', true); return; } const o = selected.root.userData, p = selected.point, localId = `CC-${Date.now().toString(36).toUpperCase()}-${Math.random().toString(36).slice(2, 6).toUpperCase()}`; const record = { feedbackId: localId, createdAt: new Date().toISOString(), elementId: o.id, elementLabel: o.label, category: o.category, text, click: [p.x, p.y, p.z], camera: [camera.position.x, camera.position.y, camera.position.z], version: 'v0.9-consolidated', qa: QA }; localStorage.setItem(`casa-feedback-${localId}`, JSON.stringify(record)); const issueTitle = `[3D] ${o.id} — ${o.label}`.slice(0, 120), issueBody = `## Feedback Casa Contreras\n\n**Feedback local:** \`${localId}\`\n**Elemento:** ${o.label}\n**ID:** \`${o.id}\`\n**Categoria:** ${o.category}\n**Versão:** v0.9-consolidated\n\n### Solicitação\n${text}\n\n### Coordenadas\n- Clique: \`${p.x.toFixed(3)}, ${p.y.toFixed(3)}, ${p.z.toFixed(3)}\`\n- Câmera: \`${camera.position.x.toFixed(3)}, ${camera.position.y.toFixed(3)}, ${camera.position.z.toFixed(3)}\`\n\n### Medidas master\n- Casa: 7,076 × 6,058 m por pavimento habitável\n- Sacada: 7,076 × 1,800 m, externa à área de moradia\n- Vão central útil: 2,200 m\n- Terreno: 10 × 25 m\n`; const url = `https://github.com/Leetattoo/casa-container/issues/new?title=${encodeURIComponent(issueTitle)}&body=${encodeURIComponent(issueBody)}`; toast(`Feedback ${localId} salvo. No GitHub clique em “Submit new issue”.`); const popup = window.open(url, '_blank'); if (!popup) location.href = url; });
if (topbar) topbar.innerHTML = `<b>CASA CONTRERAS — v0.9 CONSOLIDADA</b><br><span class="muted">1 u = 1 m • casa ${CFG.house.w.toFixed(3)} × ${CFG.house.d.toFixed(3)} m • ${grossArea.toFixed(2)} m² brutos/pavimento • sacada ${CFG.balcony.d.toFixed(2)} m 100% externa<br>WASD • mouse • 1/2/3 níveis • H escala humana • F copiar feedbacks • Q qualidade</span>`;
const startNote = document.querySelector('#start .note'); if (startNote) startNote.textContent = `Corpo residencial: ${grossArea.toFixed(2)} m² brutos por pavimento; cerca de ${clearArea.toFixed(2)} m² livres antes das divisórias. A sacada de ${balconyArea.toFixed(2)} m² é externa e não reduz a moradia.`; if (enterEl) enterEl.addEventListener('click', () => controls.lock()); controls.addEventListener('lock', () => { if (startEl) startEl.style.display = 'none'; }); controls.addEventListener('unlock', () => { if (feedbackEl.style.display !== 'grid' && startEl) startEl.style.display = 'grid'; });
const perf = { mode: 'balanced', fps: 60, dpr: Math.min(devicePixelRatio || 1, 1.0), drawCalls: 0, frames: 0, elapsed: 0 }; function applyQuality(mode) { perf.mode = mode; if (mode === 'performance') perf.dpr = Math.min(devicePixelRatio || 1, 0.82); else if (mode === 'high') perf.dpr = Math.min(devicePixelRatio || 1, 1.20); else perf.dpr = Math.min(devicePixelRatio || 1, 1.0); renderer.setPixelRatio(perf.dpr); toast(`Qualidade: ${mode} • DPR ${perf.dpr.toFixed(2)}`); } addEventListener('keydown', e => { if (e.code === 'KeyQ') { const next = perf.mode === 'balanced' ? 'performance' : perf.mode === 'performance' ? 'high' : 'balanced'; applyQuality(next); } });
const clock = new THREE.Clock(); function animate() { requestAnimationFrame(animate); const dt = Math.min(clock.getDelta(), 0.04); updateMovement(dt); updateHover(dt); renderer.render(scene, camera); perf.frames++; perf.elapsed += dt; if (perf.elapsed >= 2.0) { perf.fps = Math.round(perf.frames / perf.elapsed); perf.drawCalls = renderer.info.render.calls; if (perf.mode === 'balanced' && perf.fps < 48 && perf.dpr > 0.80) { perf.dpr = Math.max(0.80, perf.dpr - 0.10); renderer.setPixelRatio(perf.dpr); } window.__CASA_PERF__ = { ...perf, dpr: +perf.dpr.toFixed(2) }; perf.frames = 0; perf.elapsed = 0; } }
animate(); addEventListener('resize', () => { camera.aspect = innerWidth / innerHeight; camera.updateProjectionMatrix(); renderer.setSize(innerWidth, innerHeight); }); window.__CASA_SCENE__ = scene; window.__CASA_CAMERA__ = camera; window.__CASA_RENDERER__ = renderer; window.__CASA_DIMENSIONS__ = { CFG, grossArea, clearArea, balconyArea, innerW, innerD, bedroomDepth };
